# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1054, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1061, 701))
        self.tabWidget.setObjectName("tabWidget")
        self.first_step_tab = QtWidgets.QWidget()
        self.first_step_tab.setObjectName("first_step_tab")
        self.formLayoutWidget = QtWidgets.QWidget(self.first_step_tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 40, 511, 317))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(6, 3, 0, 0)
        self.formLayout.setVerticalSpacing(7)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.surname_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.surname_line.sizePolicy().hasHeightForWidth())
        self.surname_line.setSizePolicy(sizePolicy)
        self.surname_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.surname_line.setText("")
        self.surname_line.setObjectName("surname_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.surname_line)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.first_name_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.first_name_line.sizePolicy().hasHeightForWidth())
        self.first_name_line.setSizePolicy(sizePolicy)
        self.first_name_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.first_name_line.setText("")
        self.first_name_line.setObjectName("first_name_line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.first_name_line)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.father_name_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.father_name_line.sizePolicy().hasHeightForWidth())
        self.father_name_line.setSizePolicy(sizePolicy)
        self.father_name_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.father_name_line.setObjectName("father_name_line")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.father_name_line)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.gender_cmb = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gender_cmb.sizePolicy().hasHeightForWidth())
        self.gender_cmb.setSizePolicy(sizePolicy)
        self.gender_cmb.setStyleSheet("background-color: white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;")
        self.gender_cmb.setObjectName("gender_cmb")
        self.gender_cmb.addItem("")
        self.gender_cmb.addItem("")
        self.gender_cmb.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gender_cmb)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.email_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_line.sizePolicy().hasHeightForWidth())
        self.email_line.setSizePolicy(sizePolicy)
        self.email_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.email_line.setObjectName("email_line")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.email_line)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.birth_date = QtWidgets.QDateEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birth_date.sizePolicy().hasHeightForWidth())
        self.birth_date.setSizePolicy(sizePolicy)
        self.birth_date.setStyleSheet("font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;")
        self.birth_date.setObjectName("birth_date")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.birth_date)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.phone_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_line.sizePolicy().hasHeightForWidth())
        self.phone_line.setSizePolicy(sizePolicy)
        self.phone_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.phone_line.setObjectName("phone_line")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.phone_line)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.birthplace_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birthplace_line.sizePolicy().hasHeightForWidth())
        self.birthplace_line.setSizePolicy(sizePolicy)
        self.birthplace_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.birthplace_line.setText("")
        self.birthplace_line.setObjectName("birthplace_line")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.birthplace_line)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.dormitory_cmb = QtWidgets.QComboBox(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dormitory_cmb.sizePolicy().hasHeightForWidth())
        self.dormitory_cmb.setSizePolicy(sizePolicy)
        self.dormitory_cmb.setStyleSheet("background-color: white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;")
        self.dormitory_cmb.setObjectName("dormitory_cmb")
        self.dormitory_cmb.addItem("")
        self.dormitory_cmb.addItem("")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.dormitory_cmb)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.photo_of_person_btn = QtWidgets.QPushButton(self.formLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo_of_person_btn.sizePolicy().hasHeightForWidth())
        self.photo_of_person_btn.setSizePolicy(sizePolicy)
        self.photo_of_person_btn.setStyleSheet("background-color:white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size: 14px;")
        self.photo_of_person_btn.setObjectName("photo_of_person_btn")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.photo_of_person_btn)
        self.label = QtWidgets.QLabel(self.first_step_tab)
        self.label.setGeometry(QtCore.QRect(30, 10, 261, 31))
        self.label.setStyleSheet("font-family: Yu Gothic UI Semibold;\n"
"font-size: 26px;")
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.first_step_tab)
        self.line.setGeometry(QtCore.QRect(30, 32, 201, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_12 = QtWidgets.QLabel(self.first_step_tab)
        self.label_12.setGeometry(QtCore.QRect(30, 372, 471, 41))
        self.label_12.setStyleSheet("font-family: Yu Gothic UI Semibold;\n"
"font-size: 26px;")
        self.label_12.setObjectName("label_12")
        self.line_2 = QtWidgets.QFrame(self.first_step_tab)
        self.line_2.setGeometry(QtCore.QRect(30, 400, 471, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.first_step_tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 408, 511, 212))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setVerticalSpacing(7)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_17.setObjectName("label_17")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_18.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_18.setObjectName("label_18")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.photo_of_passport_btn = QtWidgets.QPushButton(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo_of_passport_btn.sizePolicy().hasHeightForWidth())
        self.photo_of_passport_btn.setSizePolicy(sizePolicy)
        self.photo_of_passport_btn.setStyleSheet("background-color:white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size: 14px;")
        self.photo_of_passport_btn.setObjectName("photo_of_passport_btn")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.photo_of_passport_btn)
        self.subdivision_code_line = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subdivision_code_line.sizePolicy().hasHeightForWidth())
        self.subdivision_code_line.setSizePolicy(sizePolicy)
        self.subdivision_code_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.subdivision_code_line.setText("")
        self.subdivision_code_line.setObjectName("subdivision_code_line")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.subdivision_code_line)
        self.who_gave_line = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.who_gave_line.sizePolicy().hasHeightForWidth())
        self.who_gave_line.setSizePolicy(sizePolicy)
        self.who_gave_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.who_gave_line.setObjectName("who_gave_line")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.who_gave_line)
        self.pasport_number_line = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pasport_number_line.sizePolicy().hasHeightForWidth())
        self.pasport_number_line.setSizePolicy(sizePolicy)
        self.pasport_number_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.pasport_number_line.setObjectName("pasport_number_line")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pasport_number_line)
        self.passport_series_line = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.passport_series_line.sizePolicy().hasHeightForWidth())
        self.passport_series_line.setSizePolicy(sizePolicy)
        self.passport_series_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.passport_series_line.setObjectName("passport_series_line")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.passport_series_line)
        self.given_date = QtWidgets.QDateEdit(self.formLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.given_date.sizePolicy().hasHeightForWidth())
        self.given_date.setSizePolicy(sizePolicy)
        self.given_date.setStyleSheet("font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;")
        self.given_date.setObjectName("given_date")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.given_date)
        self.line_3 = QtWidgets.QFrame(self.first_step_tab)
        self.line_3.setGeometry(QtCore.QRect(580, 32, 241, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_19 = QtWidgets.QLabel(self.first_step_tab)
        self.label_19.setGeometry(QtCore.QRect(580, 9, 251, 35))
        self.label_19.setStyleSheet("font-family: Yu Gothic UI Semibold;\n"
"font-size: 26px;")
        self.label_19.setObjectName("label_19")
        self.line_4 = QtWidgets.QFrame(self.first_step_tab)
        self.line_4.setGeometry(QtCore.QRect(550, 20, 10, 601))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(14)
        self.line_4.setFont(font)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(0)
        self.line_4.setMidLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.first_step_tab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(580, 40, 451, 155))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setVerticalSpacing(7)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_20.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_20.setObjectName("label_20")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.index_line = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.index_line.sizePolicy().hasHeightForWidth())
        self.index_line.setSizePolicy(sizePolicy)
        self.index_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.index_line.setText("")
        self.index_line.setObjectName("index_line")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.index_line)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_21.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_21.setObjectName("label_21")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_22.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_22.setObjectName("label_22")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_23.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_23.setObjectName("label_23")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_24.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_24.setObjectName("label_24")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.city_line = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_line.sizePolicy().hasHeightForWidth())
        self.city_line.setSizePolicy(sizePolicy)
        self.city_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.city_line.setText("")
        self.city_line.setObjectName("city_line")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.city_line)
        self.street_line = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.street_line.sizePolicy().hasHeightForWidth())
        self.street_line.setSizePolicy(sizePolicy)
        self.street_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.street_line.setText("")
        self.street_line.setObjectName("street_line")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.street_line)
        self.house_line = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.house_line.sizePolicy().hasHeightForWidth())
        self.house_line.setSizePolicy(sizePolicy)
        self.house_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.house_line.setText("")
        self.house_line.setObjectName("house_line")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.house_line)
        self.flat_line = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flat_line.sizePolicy().hasHeightForWidth())
        self.flat_line.setSizePolicy(sizePolicy)
        self.flat_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.flat_line.setText("")
        self.flat_line.setObjectName("flat_line")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.flat_line)
        self.generate_consent_btn = QtWidgets.QPushButton(self.first_step_tab)
        self.generate_consent_btn.setGeometry(QtCore.QRect(640, 360, 341, 51))
        self.generate_consent_btn.setStyleSheet("QPushButton {font-family:Yu Gothic UI ;\n"
"                    font-size: 20px;\n"
"                    background-color: #FFF44F;\n"
"                    border: 1px solid #911E42;\n"
"                    border-radius: 5px;\n"
"                    color: #911E42;\n"
"                    position: relative;\n"
"                    box-sizing: border-box;\n"
"                    transition: all 700ms ease;}\n"
"\n"
"QPushButton:hover {\n"
"    background: #911E42;\n"
"    color: #FFF44F;\n"
"    box-shadow: inset 0 0 0 3px #b84642;\n"
"}")
        self.generate_consent_btn.setObjectName("generate_consent_btn")
        self.upload_consent_btn = QtWidgets.QPushButton(self.first_step_tab)
        self.upload_consent_btn.setGeometry(QtCore.QRect(640, 430, 341, 51))
        self.upload_consent_btn.setStyleSheet("QPushButton {font-family:Yu Gothic UI ;\n"
"                    font-size: 20px;\n"
"                    background-color: #FFF44F;\n"
"                    border: 1px solid #911E42;\n"
"                    border-radius: 5px;\n"
"                    color: #911E42;\n"
"                    position: relative;\n"
"                    box-sizing: border-box;\n"
"                    transition: all 700ms ease;}\n"
"\n"
"QPushButton:hover {\n"
"    background: #911E42;\n"
"    color: #FFF44F;\n"
"    box-shadow: inset 0 0 0 3px #b84642;\n"
"}")
        self.upload_consent_btn.setObjectName("upload_consent_btn")
        self.save_changes_btn1 = QtWidgets.QPushButton(self.first_step_tab)
        self.save_changes_btn1.setGeometry(QtCore.QRect(640, 290, 341, 51))
        self.save_changes_btn1.setStyleSheet("QPushButton {font-family:Yu Gothic UI ;\n"
"                    font-size: 20px;\n"
"                    background-color: #FFF44F;\n"
"                    border: 1px solid #911E42;\n"
"                    border-radius: 5px;\n"
"                    color: #911E42;\n"
"                    position: relative;\n"
"                    box-sizing: border-box;\n"
"                    transition: all 700ms ease;}\n"
"\n"
"QPushButton:hover {\n"
"    background: #911E42;\n"
"    color: #FFF44F;\n"
"    box-shadow: inset 0 0 0 3px #b84642;\n"
"}")
        self.save_changes_btn1.setObjectName("save_changes_btn1")
        self.formLayoutWidget.raise_()
        self.label.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.formLayoutWidget_2.raise_()
        self.line_3.raise_()
        self.line_4.raise_()
        self.formLayoutWidget_3.raise_()
        self.generate_consent_btn.raise_()
        self.upload_consent_btn.raise_()
        self.label_12.raise_()
        self.label_19.raise_()
        self.save_changes_btn1.raise_()
        self.tabWidget.addTab(self.first_step_tab, "")
        self.second_step_tab = QtWidgets.QWidget()
        self.second_step_tab.setObjectName("second_step_tab")
        self.label_25 = QtWidgets.QLabel(self.second_step_tab)
        self.label_25.setGeometry(QtCore.QRect(200, 8, 451, 41))
        self.label_25.setStyleSheet("font-family: Yu Gothic UI Semibold;\n"
"font-size: 26px;")
        self.label_25.setObjectName("label_25")
        self.line_5 = QtWidgets.QFrame(self.second_step_tab)
        self.line_5.setGeometry(QtCore.QRect(200, 30, 451, 24))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.second_step_tab)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(200, 44, 661, 61))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setVerticalSpacing(7)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_26.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_26.setObjectName("label_26")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.label_27 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_27.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_27.setObjectName("label_27")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.certificate_number_line = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.certificate_number_line.sizePolicy().hasHeightForWidth())
        self.certificate_number_line.setSizePolicy(sizePolicy)
        self.certificate_number_line.setStyleSheet("QLineEdit {font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;}")
        self.certificate_number_line.setText("")
        self.certificate_number_line.setObjectName("certificate_number_line")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.certificate_number_line)
        self.certificate_photo_btn = QtWidgets.QPushButton(self.formLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.certificate_photo_btn.sizePolicy().hasHeightForWidth())
        self.certificate_photo_btn.setSizePolicy(sizePolicy)
        self.certificate_photo_btn.setStyleSheet("background-color:white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size: 14px;")
        self.certificate_photo_btn.setObjectName("certificate_photo_btn")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.certificate_photo_btn)
        self.label_28 = QtWidgets.QLabel(self.second_step_tab)
        self.label_28.setGeometry(QtCore.QRect(200, 128, 661, 41))
        self.label_28.setStyleSheet("font-family: Yu Gothic UI Semibold;\n"
"font-size: 26px;")
        self.label_28.setObjectName("label_28")
        self.line_6 = QtWidgets.QFrame(self.second_step_tab)
        self.line_6.setGeometry(QtCore.QRect(200, 154, 661, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.second_step_tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(200, 164, 661, 61))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setVerticalSpacing(7)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_29 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_29.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_29.setObjectName("label_29")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.label_30 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_30.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_30.setObjectName("label_30")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.form_of_education_cmb = QtWidgets.QComboBox(self.formLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.form_of_education_cmb.sizePolicy().hasHeightForWidth())
        self.form_of_education_cmb.setSizePolicy(sizePolicy)
        self.form_of_education_cmb.setStyleSheet("background-color: white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;")
        self.form_of_education_cmb.setObjectName("form_of_education_cmb")
        self.form_of_education_cmb.addItem("")
        self.form_of_education_cmb.addItem("")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.form_of_education_cmb)
        self.field_of_study_cmb = QtWidgets.QComboBox(self.formLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.field_of_study_cmb.sizePolicy().hasHeightForWidth())
        self.field_of_study_cmb.setSizePolicy(sizePolicy)
        self.field_of_study_cmb.setStyleSheet("background-color: white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;")
        self.field_of_study_cmb.setObjectName("field_of_study_cmb")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.field_of_study_cmb)
        self.label_31 = QtWidgets.QLabel(self.second_step_tab)
        self.label_31.setGeometry(QtCore.QRect(200, 238, 451, 41))
        self.label_31.setStyleSheet("font-family: Yu Gothic UI Semibold;\n"
"font-size: 26px;")
        self.label_31.setObjectName("label_31")
        self.line_7 = QtWidgets.QFrame(self.second_step_tab)
        self.line_7.setGeometry(QtCore.QRect(200, 270, 231, 7))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.second_step_tab)
        self.line_8.setGeometry(QtCore.QRect(200, 396, 371, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label_32 = QtWidgets.QLabel(self.second_step_tab)
        self.label_32.setGeometry(QtCore.QRect(200, 369, 381, 41))
        self.label_32.setStyleSheet("font-family: Yu Gothic UI Semibold;\n"
"font-size: 26px;")
        self.label_32.setObjectName("label_32")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.second_step_tab)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(200, 404, 661, 83))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.formLayout_6 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_33 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_33.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.ind_awards_cmb = QtWidgets.QComboBox(self.formLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ind_awards_cmb.sizePolicy().hasHeightForWidth())
        self.ind_awards_cmb.setSizePolicy(sizePolicy)
        self.ind_awards_cmb.setStyleSheet("background-color: white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;")
        self.ind_awards_cmb.setObjectName("ind_awards_cmb")
        self.ind_awards_cmb.addItem("")
        self.ind_awards_cmb.addItem("")
        self.ind_awards_cmb.addItem("")
        self.ind_awards_cmb.addItem("")
        self.ind_awards_cmb.addItem("")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ind_awards_cmb)
        self.label_34 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_34.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.photo_of_document_ia_btn = QtWidgets.QPushButton(self.formLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.photo_of_document_ia_btn.sizePolicy().hasHeightForWidth())
        self.photo_of_document_ia_btn.setSizePolicy(sizePolicy)
        self.photo_of_document_ia_btn.setStyleSheet("background-color:white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size: 14px;")
        self.photo_of_document_ia_btn.setObjectName("photo_of_document_ia_btn")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.photo_of_document_ia_btn)
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.second_step_tab)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(200, 274, 661, 80))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.formLayout_7 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.line_9 = QtWidgets.QFrame(self.second_step_tab)
        self.line_9.setGeometry(QtCore.QRect(200, 530, 351, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_35 = QtWidgets.QLabel(self.second_step_tab)
        self.label_35.setGeometry(QtCore.QRect(200, 504, 361, 41))
        self.label_35.setStyleSheet("font-family: Yu Gothic UI Semibold;\n"
"font-size: 26px;")
        self.label_35.setObjectName("label_35")
        self.formLayoutWidget_8 = QtWidgets.QWidget(self.second_step_tab)
        self.formLayoutWidget_8.setGeometry(QtCore.QRect(200, 540, 661, 41))
        self.formLayoutWidget_8.setObjectName("formLayoutWidget_8")
        self.formLayout_8 = QtWidgets.QFormLayout(self.formLayoutWidget_8)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_36 = QtWidgets.QLabel(self.formLayoutWidget_8)
        self.label_36.setStyleSheet("QLabel {font-family: Yu Gothic UI Semibold;\n"
"font-size: 19px;}")
        self.label_36.setObjectName("label_36")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.orig_or_copy_combobox = QtWidgets.QComboBox(self.formLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orig_or_copy_combobox.sizePolicy().hasHeightForWidth())
        self.orig_or_copy_combobox.setSizePolicy(sizePolicy)
        self.orig_or_copy_combobox.setStyleSheet("background-color: white;\n"
"border: 1px solid gray;\n"
"font-family: Yu Gothic UI;\n"
"font-size:14px;\n"
"padding-left:6px;")
        self.orig_or_copy_combobox.setObjectName("orig_or_copy_combobox")
        self.orig_or_copy_combobox.addItem("")
        self.orig_or_copy_combobox.addItem("")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.orig_or_copy_combobox)
        self.generate_consent_btn_2 = QtWidgets.QPushButton(self.second_step_tab)
        self.generate_consent_btn_2.setGeometry(QtCore.QRect(30, 600, 321, 51))
        self.generate_consent_btn_2.setStyleSheet("QPushButton {font-family:Yu Gothic UI ;\n"
"                    font-size: 20px;\n"
"                    background-color: #FFF44F;\n"
"                    border: 1px solid #911E42;\n"
"                    border-radius: 5px;\n"
"                    color: #911E42;\n"
"                    position: relative;\n"
"                    box-sizing: border-box;\n"
"                    transition: all 700ms ease;}\n"
"\n"
"QPushButton:hover {\n"
"    background: #911E42;\n"
"    color: #FFF44F;\n"
"    box-shadow: inset 0 0 0 3px #b84642;\n"
"}")
        self.generate_consent_btn_2.setObjectName("generate_consent_btn_2")
        self.upload_consent_btn_2 = QtWidgets.QPushButton(self.second_step_tab)
        self.upload_consent_btn_2.setGeometry(QtCore.QRect(700, 600, 321, 51))
        self.upload_consent_btn_2.setStyleSheet("QPushButton {font-family:Yu Gothic UI ;\n"
"                    font-size: 20px;\n"
"                    background-color: #FFF44F;\n"
"                    border: 1px solid #911E42;\n"
"                    border-radius: 5px;\n"
"                    color: #911E42;\n"
"                    position: relative;\n"
"                    box-sizing: border-box;\n"
"                    transition: all 700ms ease;}\n"
"\n"
"QPushButton:hover {\n"
"    background: #911E42;\n"
"    color: #FFF44F;\n"
"    box-shadow: inset 0 0 0 3px #b84642;\n"
"}")
        self.upload_consent_btn_2.setObjectName("upload_consent_btn_2")
        self.save_changes_btn2 = QtWidgets.QPushButton(self.second_step_tab)
        self.save_changes_btn2.setGeometry(QtCore.QRect(380, 600, 291, 51))
        self.save_changes_btn2.setStyleSheet("QPushButton {font-family:Yu Gothic UI ;\n"
"                    font-size: 20px;\n"
"                    background-color: #FFF44F;\n"
"                    border: 1px solid #911E42;\n"
"                    border-radius: 5px;\n"
"                    color: #911E42;\n"
"                    position: relative;\n"
"                    box-sizing: border-box;\n"
"                    transition: all 700ms ease;}\n"
"\n"
"QPushButton:hover {\n"
"    background: #911E42;\n"
"    color: #FFF44F;\n"
"    box-shadow: inset 0 0 0 3px #b84642;\n"
"}")
        self.save_changes_btn2.setObjectName("save_changes_btn2")
        self.formLayoutWidget_4.raise_()
        self.formLayoutWidget_5.raise_()
        self.label_31.raise_()
        self.line_8.raise_()
        self.formLayoutWidget_6.raise_()
        self.formLayoutWidget_7.raise_()
        self.formLayoutWidget_8.raise_()
        self.line_6.raise_()
        self.line_7.raise_()
        self.line_9.raise_()
        self.generate_consent_btn_2.raise_()
        self.upload_consent_btn_2.raise_()
        self.label_32.raise_()
        self.label_28.raise_()
        self.line_5.raise_()
        self.label_25.raise_()
        self.label_35.raise_()
        self.save_changes_btn2.raise_()
        self.tabWidget.addTab(self.second_step_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главная"))
        self.label_2.setText(_translate("MainWindow", "Фамилия"))
        self.label_3.setText(_translate("MainWindow", "Имя"))
        self.label_4.setText(_translate("MainWindow", "Отчество"))
        self.label_5.setText(_translate("MainWindow", "Пол"))
        self.gender_cmb.setItemText(0, _translate("MainWindow", "Мужчина"))
        self.gender_cmb.setItemText(1, _translate("MainWindow", "Женщина"))
        self.gender_cmb.setItemText(2, _translate("MainWindow", "Боевой вертолет"))
        self.label_6.setText(_translate("MainWindow", "E-mail"))
        self.label_7.setText(_translate("MainWindow", "Дата рождения"))
        self.label_8.setText(_translate("MainWindow", "Телефон"))
        self.label_9.setText(_translate("MainWindow", "Место рождения  "))
        self.label_10.setText(_translate("MainWindow", "Общежитие"))
        self.dormitory_cmb.setItemText(0, _translate("MainWindow", "Нужно"))
        self.dormitory_cmb.setItemText(1, _translate("MainWindow", "Не нужно"))
        self.label_11.setText(_translate("MainWindow", "Фото"))
        self.photo_of_person_btn.setText(_translate("MainWindow", "Выбрать файл"))
        self.label.setText(_translate("MainWindow", "Личные данные\n"
""))
        self.label_12.setText(_translate("MainWindow", "Документ, удостоверяющий личность "))
        self.label_13.setText(_translate("MainWindow", "Серия"))
        self.label_14.setText(_translate("MainWindow", "Номер"))
        self.label_15.setText(_translate("MainWindow", "Кем выдан"))
        self.label_16.setText(_translate("MainWindow", "Код подразделения"))
        self.label_17.setText(_translate("MainWindow", "Дата выдачи"))
        self.label_18.setText(_translate("MainWindow", "Фото/скан \n"
"первой страницы"))
        self.photo_of_passport_btn.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_19.setText(_translate("MainWindow", "Адрес регистрации"))
        self.label_20.setText(_translate("MainWindow", "Индекс"))
        self.label_21.setText(_translate("MainWindow", "Город"))
        self.label_22.setText(_translate("MainWindow", "Улица"))
        self.label_23.setText(_translate("MainWindow", "Дом"))
        self.label_24.setText(_translate("MainWindow", "Квартира"))
        self.generate_consent_btn.setText(_translate("MainWindow", "Сформировать согласие на ОПД"))
        self.upload_consent_btn.setText(_translate("MainWindow", "Загрузить согласие в систему"))
        self.save_changes_btn1.setText(_translate("MainWindow", "Сохранить изменения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.first_step_tab), _translate("MainWindow", "Tab 1"))
        self.label_25.setText(_translate("MainWindow", "Документ об образовании (аттестат)"))
        self.label_26.setText(_translate("MainWindow", "Номер документа"))
        self.label_27.setText(_translate("MainWindow", "Фото/скан титула"))
        self.certificate_photo_btn.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_28.setText(_translate("MainWindow", "Выбор формы обучения и направления поступления"))
        self.label_29.setText(_translate("MainWindow", "Форма обучения"))
        self.label_30.setText(_translate("MainWindow", "Направление"))
        self.form_of_education_cmb.setItemText(0, _translate("MainWindow", "Бюджет"))
        self.form_of_education_cmb.setItemText(1, _translate("MainWindow", "Платное"))
        self.label_31.setText(_translate("MainWindow", "Данные экзаменов"))
        self.label_32.setText(_translate("MainWindow", "Индивидуальные достижения"))
        self.label_33.setText(_translate("MainWindow", "Выбор  "))
        self.ind_awards_cmb.setItemText(0, _translate("MainWindow", "ГТО"))
        self.ind_awards_cmb.setItemText(1, _translate("MainWindow", "Аттестат с отличием (или диплом СПО)"))
        self.ind_awards_cmb.setItemText(2, _translate("MainWindow", "Всероссийская олимпиада по математике"))
        self.ind_awards_cmb.setItemText(3, _translate("MainWindow", "Всероссийская олимпиада по профильному предмету"))
        self.ind_awards_cmb.setItemText(4, _translate("MainWindow", "Предпрофессиональный экзамен"))
        self.label_34.setText(_translate("MainWindow", "Фото/скан документа,\n"
"подтверждающего ИД"))
        self.photo_of_document_ia_btn.setText(_translate("MainWindow", "Выбрать файл"))
        self.label_35.setText(_translate("MainWindow", "Подаю оригинал или копию"))
        self.label_36.setText(_translate("MainWindow", "Выбор  "))
        self.orig_or_copy_combobox.setItemText(0, _translate("MainWindow", "Оригинал"))
        self.orig_or_copy_combobox.setItemText(1, _translate("MainWindow", "Копию"))
        self.generate_consent_btn_2.setText(_translate("MainWindow", "Сформировать pdf"))
        self.upload_consent_btn_2.setText(_translate("MainWindow", "Загрузить pdf в систему"))
        self.save_changes_btn2.setText(_translate("MainWindow", "Сохранить изменения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.second_step_tab), _translate("MainWindow", "Tab 2"))
